language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: BGp26cMSOc+ir05euO0KnyjedzXevgAmOSvKFv0w/Ih0/SGHRdlBToTfGS8+8YxZ1/jwH701pMd0tgPHcs0cEGiClrB64u1dsZt895Cgxe/ee7v3vtTv2kNyuw8nJeUP2v8l0lPelS1U5Mx9Utl5j0g1Y0/oAeQRpCF07H4b0bkhsPUzQVBx7Y7JtMJVoS8SE106TgCD0UC0NslDpPT37/TrqpWJyug0EkX6RSQL/DLgrTC8C+GtP+Pa/lfNyY8if4urzwErn1yVvUK2g7u+P/Ti2FiDdtZEx+SkuDxp+EqFxGEEzvi2m0a9O9KpK0b/c1QqyVGAaqsbGiYxplVM4Vm4e33OVhN+PuHIz+e9kmbLawE/yhP3VWFV6bBUvOm8lBfZ9RxTBIBZFsUN84p3Gtfe730J+qg/1sHJf0sLhZ/ezJ1eC622dD87HJ+Elbjv/EGCcLWAt22JSAtAhgHHpP1ljGckwIlHuNxIBQWFpmpU61wcedeeoKkqGT8B4QDoGQzG3tfqcsd0UmraFt7jN5bLl+rXdC2Pbg8ybcz+1gheyGr+vUOC7IjpHTGCcExo66t1hpUqb1nhn4smQnclZHxr+j1dBg4yMzKQjSW0/0qfGl4gXFbB1Wtb69d+RLC0bCNPOx5R93xOtxunUU9bQD0VYuTfDkxdCb+sr6Mcr8s=
  app: hidden-reaches-76537
  on:
    repo: chase2themac/recipe-testing
