language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: KRRe3DOpAlX9KEjWpmcPWPSaeLBj6cal1KRLtEkGBMkkCxd4vGWC8lNzEkc2AjtHf/LEWu661YfzVEWbz/3SyxHu+KQrZIN9FZiChrjgjL8V47/siCVkPMVus6Vp36ICzx95b5aQAYRGllSge2nHPVe2Flv6+5JM+ZVCeq+1z6LlAPUJbyUMIBIlvt73G3C4+ydS9TOTP0mUW11wJ/g4oz2aGIYRxB+TmluqmFIbrRgYA+qP1bpQVVhvG8AdEDpOl2A6+e5Y2WbW2RuL41vimmd5kKUJ/EKK4gAlbwudkHfLPM5T+9xnFE1jh8lZTPriWeWZ4oZ6v0NYm6gRoGCeyntmUnDZ6eNpfqazitcJOcQWq19wXFtQNRNwJV49m4/kFYnkFB8wh4/MDYXdYnNLH+TKoBSQeB+3Y0/j9dTALbbc2pixH+7UlePSwL1wZj455nqGFVlS/nE6BxH/VyrlTFm+bCC/Y3OM/+GvnZGSo1yfNNn6gYWJGhsQwY68lHDhHNkjsEP2GRVAqeAYy4bf6SnAJDPLCAGGsg+UrPn4ebzhFyvNk1gTAjKjyCgKGA3zvat1CS9q/yLTXicjzHnm4o2zjXSGehzGmocQ2qIeasbXxzIPHw15YSudY+DilIMlMuMoqyvpbVXFpNomEQDZ+A0iJOyPF8Ts8VPL99dV0Hw=
  app: hidden-reaches-76537
  on:
    repo: chase2themac/recipe-testing
